name: Notify Canada Internships

on:
  schedule:
    # Runs every hour
    - cron: "0 * * * *"
  workflow_dispatch: # Manual trigger

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Try to restore notified.json from previous runs, ignore if not found
      - name: Restore notified.json
        id: restore
        uses: actions/download-artifact@v4
        with:
          name: notified-json
          path: .
        continue-on-error: true

      # Ensure notified.json exists even if this is the first run
      - name: Ensure notified.json exists
        run: |
          if [ ! -f notified.json ]; then
            echo "[]" > notified.json
            echo "Created empty notified.json for first run."
          else
            echo "Restored existing notified.json."
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Run Canada Internship Notifier
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python notify_canada_interns.py

      # Upload the updated notified.json for the next run. Working
      - name: Save notified.json
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: notified-json
          path: notified.json

